refactor: importable module and event struct
trudi-group/ipfs-metric-exporter pull request #53
Opened 2023-01-17 21:51 UTC by mg98

- Renamed module so that external projects can `go get github.com/trudi-group/ipfs-metric-exporter`
- Made `type event struct` public

2023-01-18 07:12 UTC, mrd0ll4r requested changes
A few nitpicks

2023-01-18 07:12 UTC, mrd0ll4r commented on metricplugin/rabbitmq.go
> +		logger.Debugf("packager: got Event %+v, now have %d events in buffer", msg, len((**currentBuffer).events))
leave this as it was, because it's an English sentence

2023-01-18 07:12 UTC, mrd0ll4r commented on metricplugin/rabbitmq.go
> +type Event struct {
This will probably need a godoc comment :)

2023-01-18 07:14 UTC, mrd0ll4r commented
Ah, and the checks have something to say

2023-01-18 13:32 UTC, mrd0ll4r requested changes

2023-01-18 13:32 UTC, mrd0ll4r commented on metricplugin/api.go
> +	// The type of this Event.
I wouldn't capitalize here, either. Sorry for missing this last time...

2023-01-19 08:12 UTC, mrd0ll4r commented
`gofumpt` complains because imports should be grouped into stdlib and others, see [https://github.com/mvdan/gofumpt#added-rules](their added rules), especially the one about `std imports must be in a separate group at the top`.

2023-01-19 09:08 UTC, mrd0ll4r commented
Fantastic, I think this should pass CI. Can you squash the commits into one, so I can merge?

2023-01-19 10:06 UTC, mg98 commented
Doesn't Github do it for you?

2023-01-19 10:22 UTC, mrd0ll4r commented
It does, but I remember from somewhere that something about it is broken and I since stopped doing it... It will definitely break signing, which we don't use here, but it feels weird in general.

2023-01-19 10:23 UTC, mrd0ll4r approved these changes

2023-01-19 10:23 UTC, merged